### PR TITLE
Update header

### PR DESCRIPTION
**Pull request by minad**
Start with version 0.1, update authors, maintainers and copyright.

### CODE REVIEW

**Comment by minad** [comment]
@Crandel Can you please relax the review criteria? It is not necessary and will stand of the way of fast iterations. One can still enforce stronger limits if problems occur.

**Comment by minad** [comment]
Not sure what kind of branch protections make sense - maybe requiring the CI to run is not a bad idea. On the other hand we have very little code here.

**Review by Crandel — APPROVED** [review]

**Comment by Crandel** [comment]
The only requirement is to have at least one approval from maintainers. I don't want to merge unchecked changes. Your and @mpenet approvals should also be valid.

**Comment by minad** [comment]
Okay, but maintainers should be able to push directly? I am not.

**Comment by Crandel** [comment]
I'm not able to push directly too. Only via PR. I don't see any options how to protect branch to other users and allow to push for maintainers.

**Comment by minad** [comment]
Okay. I don't like the PR based workflow, but I think people can adapt to that. It shouldn't be a major obstacle.

However I would like to understand - is the situation such that you can merge without review, but other maintainers/contributors of the repository cannot? If yes, then the maintainers are not treated as equal. This would be the basis for equal collaboration as I imagined in the discussion in https://github.com/melpa/melpa/pull/8282.

**Comment by minad** [comment]
My point is that the "trustworthiness check" of maintainers should be performed before adding someone as maintainer/contributor. After that, they should be free to push or merge PRs. I don't think that this is not a high-profile project, so there isn't much to worry, or is there?

**Comment by Crandel** [comment]
This is my first public cooperation, so I have no idea, how to grant you such access. Can you guide me how to do it?

**Comment by minad** [comment]
I am not sure. I think you just have to relax some the settings in the repository, the branch protection? Maybe it is not possible. Maybe the review required setting will be implied if you disallow pushing to the main branch?

**Comment by minad** [comment]
I guess, I would just relax all the checks for simplicity and instead put trust into the contributors. Note that many people have the right to push to Emacs master directly (without CI, without review, without anything!). I don't see a good reason to be more strict here.

**Comment by Crandel** [comment]
OK, I removed approval check, but let's leave PR requirements for visibility

**Comment by minad** [comment]
Okay, sounds good. I think one could later add such strict review criteria if more and more people are added, such that it is better to have cross checks. But honestly, I don't see that happening. The group of maintainers will probably stay small.

**Comment by Crandel** [comment]
Yes, make sense

**Pull request merged**
